<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>FXTVLogo.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="FXTVLogo.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Controls\LobbyControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
  </ItemGroup>

</Project>
